-- Cadastrando Produtos Iniciais
INSERT INTO PRODUTO (CODIGO, DESCRICAO, TIPO, QUANTIDADE_ESTOQUE, VALOR_FORNECEDOR, DATA_CADASTRO, DATA_ATUALIZACAO) VALUES ('ELEC001', 'Smartphone Samsung S24', 'ELETRONICO', 10, 3500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, TIPO, QUANTIDADE_ESTOQUE, VALOR_FORNECEDOR, DATA_CADASTRO, DATA_ATUALIZACAO) VALUES ('ELET001', 'Geladeira Brastemp', 'ELETRODOMESTICO', 5, 2800.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, TIPO, QUANTIDADE_ESTOQUE, VALOR_FORNECEDOR, DATA_CADASTRO, DATA_ATUALIZACAO) VALUES ('MOV001', 'Cadeira Escritório Gamer', 'MOVEL', 15, 850.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO MOVIMENTO_ESTOQUE (PRODUTO_ID, TIPO, QUANTIDADE_MOVIMENTADA, VALOR_VENDA, DATA_CADASTRO, DATA_ATUALIZACAO, DATA_VENDA) VALUES (1, 'ENTRADA', 10, 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO MOVIMENTO_ESTOQUE (PRODUTO_ID, TIPO, QUANTIDADE_MOVIMENTADA, VALOR_VENDA, DATA_CADASTRO, DATA_ATUALIZACAO, DATA_VENDA) VALUES (2, 'ENTRADA', 5, 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO MOVIMENTO_ESTOQUE (PRODUTO_ID, TIPO, QUANTIDADE_MOVIMENTADA, VALOR_VENDA, DATA_CADASTRO, DATA_ATUALIZACAO, DATA_VENDA) VALUES (3, 'ENTRADA', 15, 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO MOVIMENTO_ESTOQUE (PRODUTO_ID, TIPO, QUANTIDADE_MOVIMENTADA, VALOR_VENDA, DATA_CADASTRO, DATA_ATUALIZACAO, DATA_VENDA) VALUES (3, 'SAIDA', 5, 1000.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);